["PH","Physik"],
["B","Biologie"],
["MU","Musik"],
["CH","Chemie"],
["SP","Sport"],
["EK","Erdkunde"],
["D","Deutsch"],
["M","Mathe"],
["E5","Englisch"],
["S","Spanisch"],
["L","Latein"],
["F5","Französisch ab 5. Klasse"],
["F7","Französisch ab 7. Klasse"],
["EW","Erziehungswissenschaften"],
["SW","SoWi"],
["PK","Politik"],
["PA","Pädagogik"],
["GE","Geschichte"],
["KU","Kunst"],
["KR","Katholische Religion"],
["ER","Evangelische Religion"],
["IF","Informatik"],
["VTM","Vertiefung Mathe"],
["VTE","Vertiefung Englisch"],
